### ISSUE TITLE
Exception when changing the password

### ISSUE THREAD

**Issue by broadwaylamb** [grishka/Smithereen#79]
```
java.lang.IllegalStateException: You need to pass an existing connection to use this
	at smithereen.storage.sql.SQLQueryBuilder.execute(SQLQueryBuilder.java:248)
	at smithereen.storage.SessionStorage.getSaltFromDatabase(SessionStorage.java:480)
	at smithereen.storage.SessionStorage.updatePassword(SessionStorage.java:341)
	at smithereen.controllers.UsersController.changePassword(UsersController.java:405)
	at smithereen.routes.SettingsRoutes.updatePassword(SettingsRoutes.java:131)
	at smithereen.sparkext.CSRFSimpleRoute.handle(CSRFSimpleRoute.java:13)
	at smithereen.sparkext.CSRFRoute.handle(CSRFRoute.java:19)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1547)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
```

**How to reproduce**: go to My Settings and try to change the password.

**Comment by broadwaylamb** [comment]
That was fast. Thanks!
